### PR TITLE
Ensure a folder is opened before running commands

### LINKED ISSUE #204: running the contributed command
Signing in to VSTS using the extension fails.
teamextension

### PR DESCRIPTION
**Pull request by jeffyoung**
These changes should resolve #204

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -18,59 +18,38 @@ export async function activate(context: ExtensionContext) {
...
-    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.ShowOutput, () => _extensionManager.Tfvc.ShowOutput()));
-    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.ResolveKeepYours, (...args) => {
-            _extensionManager.Tfvc.Resolve(args ? args[0] : undefined, AutoResolveType.KeepYours);
-        }));
-    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.ResolveTakeTheirs, (...args) => {
-            _extensionManager.Tfvc.Resolve(args ? args[0] : undefined, AutoResolveType.TakeTheirs);
-        }));
-    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.Checkin, () => _extensionManager.Tfvc.Checkin()));
-    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.Sync, () => _extensionManager.Tfvc.Sync()));
+    context.subscriptions.push(commands.registerCommand(TfvcCommandNames.UndoAll, () => _extensionManager.RunAsyncCommand(() => _extensionManager.Tfvc.UndoAll())));
```
Comment (jpricketMSFT) [inline src/extension.ts]: I am wondering if this should be "RunAsyncCommand( async () =>"
I am not sure if it matters but may be more correct

Comment (jeffyoung) [inline src/extension.ts]: As it turns out, in this instance, I don't even need RunAsyncCommand. Another commit coming.
